apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-node-rotator
  labels:
    app: {{ .Release.Name }}-node-rotator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-node-rotator
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-node-rotator
    spec:
      {{- if .Values.nodeRotator.nodeSelector }}
      nodeSelector: {{ .Values.nodeRotator.nodeSelector | toJson }}
      {{- end }}
      containers:
      - name: rotator
        image: {{ .Values.nodeRotator.image.repository }}:{{ .Values.nodeRotator.image.tag }}
        env:
        - name: TARGET_NODE_SELECTOR
          value: {{ .Values.nodeRotator.targetNodeSelector | quote }}
        - name: IN_CLUSTER
          value: "true"
        - name: REPLICAS
          value: {{ .Values.nodeRotator.replicas | quote }}
