apiVersion: v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-node-rotator
  labels:
    app: {{ .Release.Name }}-node-rotator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-node-rotator
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-node-rotator
    spec:
      {{- if .Values.nodeRotator.nodeSelector }}
      nodeSelector: {{ .Values.nodeRotator.nodeSelector | toJson }}
      {{- end }}
      containers:
      - name: glider
        image: nadoo/glider:v0.15.0
        args: ['-listen', ':8443']
        ports:
        - containerPort: 8443
