apiVersion: v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-proxy
  labels:
    app: {{ .Release.Name }}-proxy
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-proxy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-proxy
    spec:
      {{- if .Values.proxy.nodeSelector }}
      nodeSelector: {{ .Values.proxy.nodeSelector | toJson }}
      {{- end }}
      containers:
      - name: glider
        image: {{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}
        args: ['-listen', ':8443']
        ports:
        - containerPort: 8443
