apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy
  {{- with .Values.proxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.proxy.service.type }}
  selector:
    app: {{ .Release.Name }}-proxy
  ports:
    - protocol: TCP
      port: {{ .Values.proxy.service.port }}
      targetPort: 8443
