name: ci-docker

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: set_var
        name: Set Image Tag as Cargo Package Version
        run: |
          content="$(cat ./node-rotator/package.json | grep '"version": "' | awk -F'[ ",:]+' '$1 == 'version' { print $3 }')"
          # end of optional handling for multi line json
          echo "::set-output name=VERSION::$content"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: node-rotator
          push: true
          tags: song9446/node-rotator:${{ steps.set_var.outputs.VERSION }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
